# Generated by Django 3.1.5 on 2021-12-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenom', models.CharField(default='', max_length=50)),
                ('Date_Naissance', models.DateField()),
                ('sex', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='', max_length=6)),
                ('groupe_Sanguin', models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('O-', 'O-'), ('A-', 'A-'), ('AB+', 'AB+'), ('B-', 'B-'), ('AB-', 'AB-')], default='', max_length=3)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('Date_Consultation', models.DateField()),
                ('Poids', models.FloatField(default='')),
                ('Tension', models.CharField(default='', max_length=20)),
                ('Taille', models.FloatField(default='')),
                ('Observation', models.TextField(default='', max_length=5000)),
            ],
        ),
    ]
